[package]
name = "roadrunner"
version = "0.1.0"
authors = ["valery"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
futures = "0.3.4"
structopt = "0.3.9"